In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_11d6882aba4a4088b92e5b1911d45304 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='JewUcbNRXB-WjdcpmlCmc2gLkA03KGmtZTKjPhrUYYTF',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_11d6882aba4a4088b92e5b1911d45304.get_object(Bucket='day4hc2022-donotdelete-pr-azvuzxn2f91tgo',Key='50_Startups.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
#df= pd.read_csv("50_startups.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [4]:
df.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
df["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df["State"]= le.fit_transform(df["State"])

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [8]:
x= df.iloc[:,0:4].values
y= df.iloc[:,4:5].values

In [9]:
x.shape

(108, 4)

In [10]:
y.shape

(108, 1)

In [11]:
#one hot encoder- convert numerical data into categorical data

In [12]:
from sklearn.preprocessing import OneHotEncoder
one= OneHotEncoder()
z= one.fit_transform(x[:,3:4]).toarray()

In [13]:
z

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [14]:
x= np.delete(x,3,axis=1)

In [15]:
x.shape

(108, 3)

In [16]:
x= np.concatenate((z,x),axis=1)

In [17]:
x.shape

(108, 6)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
x_train.shape

(86, 6)

In [20]:
x_test.shape

(22, 6)

In [21]:
#model building

In [22]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
ypred= lr.predict(x_test)
ypred

array([[ 48466.75433417],
       [134429.39628446],
       [ 76093.94745793],
       [181201.94746511],
       [113069.45110036],
       [134397.50337433],
       [128842.89457941],
       [159664.83856912],
       [116952.09718498],
       [ 46372.47771261],
       [102406.37641003],
       [115207.87076438],
       [ 48466.75433417],
       [119345.51846305],
       [ 88717.92542862],
       [127301.68084921],
       [127301.68084921],
       [ 91145.83032983],
       [ 58337.13774601],
       [146474.04747225],
       [149038.44713346],
       [152718.63782935]])

In [24]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

In [25]:
from sklearn.metrics import r2_score
acc= r2_score(ypred,y_test)
acc

0.9316315637551433

In [26]:
yp= lr.predict([[1,0,0,1242345,12345,234567]])
yp

array([[1025521.22961557]])